# Generated by Django 4.1.1 on 2022-09-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "wallpaper",
                    models.ImageField(blank=True, null=True, upload_to="portada"),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("quote", models.CharField(blank=True, max_length=500, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
