# Generated by Django 4.1.1 on 2022-09-14 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_portada"),
    ]

    operations = [
        migrations.DeleteModel(name="Testimonial",),
    ]
