# Generated by Django 4.1.1 on 2022-09-21 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contactprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
